<?php
/**
 * @var YotpoReviews $block
 * @var Magento\Framework\Escaper $escaper
 */

use Yotpo\Reviews\Block\Adminhtml\Dashboard\Tab\YotpoReviews;

$escaper = $escaper ?? $block;
?>
<?php if ($block->isAppKeyAndSecretSet()): ?>
    <div class="yotpo-reviews-totals" id="yotpo_reviews_totals">
        <?php if (count($block->getTotals()) > 0): ?>
            <ul class="yotpo-reviews-totals-list">
                <?php foreach ($block->getTotals() as $_total): ?>
                    <li class="yotpo-reviews-totals-item <?= $escaper->escapeHtmlAttr($_total['class']) ?>">
                        <span class="yotpo-reviews-totals-label">
                            <?= $escaper->escapeHtmlAttr($_total['label']) ?>
                        </span>
                        <strong class="yotpo-reviews-totals-value">
                            <?= $escaper->escapeHtmlAttr($_total['value']) ?>
                        </strong>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <div class="yotpo-reviews-totals-nodata">
                <?= $escaper->escapeHtml(__("No Data Found")) ?>
            </div>
        <?php endif; ?>
    </div>
    <div><?= $block->getLounchYotpoButtonHtml('MagentoAdmin_Dashboard') ?></div>
<?php else: ?>
    <div class="yotpo-reviews-totals-no-appkey">
        <div class="collect-and-leverage">
            <?= $escaper->escapeHtml(__("Collect and leverage customer reviews, ratings, and Q&A")) ?><br>
            <?= $escaper->escapeHtml(__("with Yotpo's AI-powered tools and on-site widgets.")) ?>
        </div>
        <div><?= $block->getLounchYotpoButtonHtml('MagentoAdmin_Dashboard') ?></div>
        <div class="already-have-account">
            <?= $escaper->escapeHtml(__("Already have an account?")) ?>
            <a href="<?= $escaper->escapeUrl($block->getYotpoConfigUrl()) ?>"
               title="<?= $escaper->escapeHtmlAttr(__("Connect Yotpo")) ?>">
                <?= $escaper->escapeHtml(__("Connect Yotpo")) ?>
            </a>
        </div>
    </div>
<?php endif; ?>
