<?php
/**
 * @var Reviews $block
 * @var Magento\Framework\Escaper $escaper
 */

use Yotpo\Reviews\Block\Adminhtml\Report\Reviews;

$escaper = $escaper ?? $block;
?>
<?php if ($block->isEnabled() && $block->isAppKeyAndSecretSet()):
    $periods = $block->getPeriods(); ?>
    <div class="yotpo-reviews-totals-container">
        <div class="yotpo-reviews-totals" id="yotpo_reviews_totals">
            <div class="yotpo-reports-period-select admin__action-dropdown-wrap">
                <a
                    href="#"
                    class="admin__action-dropdown"
                    title="<?= $escaper->escapeHtml(__('Time Period')) ?>"
                    data-mage-init='{"dropdown":{}}'
                    data-toggle="dropdown">
                    <span class="admin__action-dropdown-text">
                        <span><?= $escaper->escapeHtml($periods[$block->getPeriod('30d')]) ?></span>
                    </span>
                </a>
                <ul class="admin__action-dropdown-menu">
                    <?php foreach ($periods as $_period => $_label): ?>
                        <li>
                            <a
                                href="<?= $escaper->escapeHtmlAttr($block->getReviewsPeriodUrl($_period)) ?>"
                                title="<?= $escaper->escapeHtmlAttr(__($_label)) ?>">
                                <?= $escaper->escapeHtml(__($_label)) ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="yotpo-at-a-glance">
                <?= $escaper->escapeHtml(__("Yotpo at a glance")) ?>
            </div>
            <div class="user-generated-content">
                <?= $escaper->escapeHtml(__("User-generated content metrics gathered from your Yotpo dashboards.")) ?>
            </div>
            <?php if (count($block->getTotals()) > 0): ?>
                <ul class="yotpo-reviews-totals-list">
                    <?php foreach ($block->getTotals() as $_total): ?>
                        <li class="yotpo-reviews-totals-item <?= $escaper->escapeHtmlAttr($_total['class']) ?>">
                            <i class="yotpo-reviews-totals-icon"></i>
                            <strong class="yotpo-reviews-totals-value">
                                <?= $escaper->escapeHtml($_total['value']) ?>
                            </strong>
                            <span class="yotpo-reviews-totals-label">
                                <?= $escaper->escapeHtml($_total['label']) ?>
                            </span>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                <div class="yotpo-reviews-totals-nodata">
                    <?= $escaper->escapeHtml(__("No Data Found")) ?>
                </div>
            <?php endif; ?>
        </div>
        <div><?= $block->getLounchYotpoButtonHtml() ?></div>
        <div>
            <a class="yotpo-settings"
               href="<?= $escaper->escapeUrl($block->getYotpoConfigUrl()) ?>"
               title="<?= $escaper->escapeHtmlAttr(__("Yotpo Settings")) ?>">
                    <?= $escaper->escapeHtml(__("Yotpo Settings")) ?>
            </a>
        </div>
    </div>
    <style>
        .yotpo_reviews-report-reviews #anchor-content.page-content {
            background-color: #f8f8f8;
            margin-top: 115px;
        }
        .yotpo_reviews-report-reviews #anchor-content.page-content > .page-main-actions{
            margin-top: -100px;
            margin-bottom: 63px;
        }
    </style>
<?php else: ?>
    <div class="yotpo-reviews-totals-no-appkey">
        <div class="yotpo-title-content-container">
            <h2><?= $escaper->escapeHtml(__("Great brands are built<br>on happy customers"), ['br']) ?></h2>
            <p><?= $escaper->escapeHtml(__("Yotpo is already installed in your Magento store!")) ?></p>
            <p><?= $escaper->escapeHtml(__("Connect your Yotpo account to your store to accelerate growth")) ?></p>
            <?php // phpcs:ignore ?>
            <p><?= $escaper->escapeHtml(__("with a full suite of solutions for customer reviews and visual marketing.")) ?></p>
            <div><?= $block->getLounchYotpoButtonHtml('MagentoAdmin_reviews') ?></div>
            <div class="already-have-account">
                <?= $escaper->escapeHtml(__("Already have an account?")) ?>
                <?php // phpcs:ignore ?>
                <a href="<?= $escaper->escapeUrl($block->getYotpoConfigUrl()) ?>" title="<?= $escaper->escapeHtmlAttr(__("Connect Yotpo")) ?>">
                    <?= $escaper->escapeHtml(__("Connect Yotpo")) ?>
                </a>
            </div>
        </div>
        <div class="yotpo-shaddow-boxes-container">
            <div class="yotpo-shaddow-box">
                <h3><?= $escaper->escapeHtml(__("Reviews & Ratings")) ?></h3>
                <?php // phpcs:ignore ?>
                <img src='<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Yotpo_Reviews::images/reviews_and_ratings.jpg')) ?>'
                     alt="<?= $escaper->escapeHtml(__("Reviews & Ratings")) ?>">
                <?php // phpcs:ignore ?>
                <p><?= $escaper->escapeHtml(__("Turn customer content into sales by collecting and leveraging reviews, ratings, and Q&A with Yotpo’s AI-powered solutions.")) ?></p>
            </div>
            <div class="yotpo-shaddow-box">
                <h3><?= $escaper->escapeHtml(__("Visual Marketing")) ?></h3>
                <?php // phpcs:ignore ?>
                <img src='<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Yotpo_Reviews::images/visual_marketing.jpg')) ?>'
                     alt="<?= $escaper->escapeHtml(__("Visual Marketing")) ?>">
                <?php // phpcs:ignore ?>
                <p><?= $escaper->escapeHtml(__("Collect, curate, and showcase customer photos and videos in fully customizable shoppable galleries across your site.")) ?></p>
            </div>
            <div class="yotpo-shaddow-box">
                <h3><?= $escaper->escapeHtml(__("Consumer Insights")) ?></h3>
                <?php // phpcs:ignore ?>
                <img src='<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Yotpo_Reviews::images/consumer_insights.png')) ?>'
                     alt="<?= $escaper->escapeHtml(__("Consumer Insights")) ?>">
                <?php // phpcs:ignore ?>
                <p><?= $escaper->escapeHtml(__("Understand what customers are saying about your brand and products and make data-driven business decisions with actionable insights.")) ?></p>
            </div>
        </div>
    </div>
    <style>
        .yotpo_reviews-report-reviews .page-wrapper {
            background-image: linear-gradient(to bottom, #fdffff, #eff9ff);
        }
    </style>
<?php endif; ?>
