<?php
/**
 * @var $block Yotpo
 * @var Magento\Framework\Escaper $escaper
 */

use Magento\Review\Block\Product\ReviewRenderer;
use Yotpo\Reviews\Model\Config as YotpoConfig;

$escaper = $escaper ?? $block;
?>
<?php if (!($block->isEnabled() && ($block->isRenderBottomline() || $block->isRenderBottomlineQna()))) {
    return;
} ?>

<!-- Yotpo - BottomLine -->
<?php if ($block->isV3StarRatingWidget()): ?>
    <div
        class="yotpo-widget-instance"
        data-yotpo-instance-id="<?= $block->getStarRatingInstanceId() ?>"
        data-yotpo-product-id="<?= $escaper->escapeHtmlAttr($block->getProductId()) ?>"
        data-yotpo-name="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
        data-yotpo-url="<?= $escaper->escapeHtmlAttr($block->getProductUrl()) ?>"
        data-yotpo-image-url="<?= $escaper->escapeHtmlAttr($block->getProductImageUrl()) ?>"
        data-yotpo-description="<?= $escaper->escapeHtmlAttr($block->getProductDescription()) ?>"
        data-yotpo-section-id="<?= $escaper->escapeHtmlAttr(YotpoConfig::getWidgetSectionId(ReviewRenderer::DEFAULT_VIEW)) ?>"
    ></div>
<?php else: ?>
    <?php if ($block->isRenderBottomline()): ?>
        <div
            class="yotpo bottomLine bottomline-position"
            data-product-id="<?= $escaper->escapeHtmlAttr($block->getProductId()) ?>"
            data-url="<?= $escaper->escapeUrl($block->getProductUrl()) ?>">
        </div>
    <?php endif; ?>
    <?php if ($block->isRenderBottomlineQna()): ?>
        <div
            class="yotpo QABottomLine"
            data-appkey="<?= $escaper->escapeHtmlAttr($block->getAppKey()) ?>"
            data-product-id="<?= $escaper->escapeHtmlAttr($block->getProductId()) ?>">
        </div>
    <?php endif; ?>
<?php endif; ?>
<!--/ Yotpo - BottomLine -->
