<?php
/**
 * @var $block Yotpo
 * @var Magento\Framework\Escaper $escaper
 */

$escaper = $escaper ?? $block;
?>
<?php if (!($block->isEnabled() && $block->isRenderPromotedProducts() && $block->isV3PromotedProductsWidget())) {
    return;
} ?>
<!-- Yotpo - Promoted Products Widget -->
<?php if ($block->hasProduct()): ?>
    <div
        class="yotpo-widget-instance"
        data-yotpo-instance-id="<?= $block->getPromotedProductsInstanceId() ?>"
        data-yotpo-product-id="<?= $escaper->escapeHtmlAttr($block->getProductId()) ?>"
    ></div>
<?php else: ?>
    <div
        class="yotpo-widget-instance"
        data-yotpo-instance-id="<?= $block->getPromotedProductsInstanceId() ?>"
    ></div>
<?php endif; ?>
<!--/ Yotpo - Promoted Products Widget -->
