<?php
/**
 * @var $block Yotpo
 * @var Magento\Framework\Escaper $escaper
 */

use Yotpo\Reviews\Block\Yotpo;

$escaper = $escaper ?? $block;
?>
<?php if (!($block->isEnabled() && $block->isRenderBottomlineQna())) {
    return;
} ?>
<!-- Yotpo - Q&A -->
<?php if ($block->isV3QuestionsAndAnswersWidget()): ?>
    <div
        class="yotpo-widget-instance"
        data-yotpo-instance-id="<?= $block->getQuestionsAndAnswersInstanceId() ?>"
        data-yotpo-product-id="<?= $escaper->escapeHtmlAttr($block->getProductId()) ?>"
        data-yotpo-name="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
        data-yotpo-url="<?= $escaper->escapeHtmlAttr($block->getProductUrl()) ?>"
        data-yotpo-image-url="<?= $escaper->escapeHtmlAttr($block->getProductImageUrl()) ?>"
        data-yotpo-description="<?= $escaper->escapeHtmlAttr($block->getProductDescription()) ?>">
    </div>
<?php endif; ?>
<!--/ Yotpo - Q&A -->
