<?php
/**
 * @var $block Yotpo
 * @var Magento\Framework\Escaper $escaper
 */

$escaper = $escaper ?? $block;
?>
<?php if (!($block->isEnabled() && $block->isRenderReviewsTab())) {
    return;
} ?>
<!-- Yotpo - Reviews Tab Widget -->
<?php if ($block->isV3ReviewsTabWidget()): ?>
    <div
        class="yotpo-widget-instance"
        data-yotpo-instance-id="<?= $block->getReviewsTabInstanceId() ?>"
        data-yotpo-product-id="<?= $escaper->escapeHtmlAttr($block->getProductId()) ?>"
    ></div>
<?php endif; ?>
<!--/ Yotpo - Reviews Tab Widget -->
