<?php
/**
 * @var $block Yotpo
 * @var Magento\Framework\Escaper $escaper
 */

use Yotpo\Reviews\Block\Yotpo;

$escaper = $escaper ?? $block;
?>
<?php if (!$block->isEnabled()) {
    return;
}
// phpcs:disable
?>
<!-- Yotpo - Add body class -->
<script>
    (function(){require(["jquery"],function($){$(document).ready(function() {$('body').addClass('yotpo-yotpo-is-enabled');});});})();
</script>
<!--/ Yotpo - Add body class -->
<!-- Yotpo - Widget Script -->
<?php if ($block->isV3ReviewsWidget() || $block->isV3StarRatingWidget()): ?>
    <script type="text/javascript" src="https://cdn-widgetsrepository.yotpo.com/v1/loader/<?= $block->getAppKey() ?>" async></script>
<?php else: ?>
    <script>
        (function e(){var e=document.createElement("script");e.type="text/javascript",e.async=true,e.src="<?= $block->getYotpoWidgetUrl() ?>";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)})();
    </script>
<?php endif; ?>
<!--/ Yotpo - Widget Script -->
