<?php
/**
 * @var Yotpo\Reviews\Block\Yotpo $block
 * @var Magento\Framework\Escaper $escaper
 */
?>
<?php if (!($block->isEnabled() && $block->isRenderWidget() && $block->hasProduct())) {
    return;
}
$escaper = $escaper ?? $block;
?>
<!-- Yotpo - Widget Div -->
<?php if ($block->isV3ReviewsWidget()): ?>
    <div
        class="yotpo-widget-instance"
        data-yotpo-instance-id="<?= $block->getReviewsInstanceId() ?>"
        data-yotpo-product-id="<?= $escaper->escapeHtmlAttr($block->getProductId()) ?>"
        data-yotpo-name="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
        data-yotpo-url="<?= $escaper->escapeHtmlAttr($block->getProductUrl()) ?>"
        data-yotpo-price="<?= $escaper->escapeHtmlAttr($block->getProductFinalPrice()) ?>"
        data-yotpo-currency="<?= $escaper->escapeHtmlAttr($block->getCurrentCurrency()) ?>"
        data-yotpo-image-url="<?= $escaper->escapeHtmlAttr($block->getProductImageUrl()) ?>"
        data-yotpo-description="<?= $escaper->escapeHtmlAttr($block->getProductDescription()) ?>">
    </div>
<?php elseif ($block->isRenderWidget()): ?>
    <div class="yotpo yotpo-main-widget"
        data-product-id="<?= $escaper->escapeHtmlAttr($block->getProductId()) ?>"
        data-name="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
        data-description="<?= $escaper->escapeHtmlAttr($block->getProductDescription()) ?>"
        data-url="<?= $escaper->escapeHtmlAttr($block->getProductUrl()) ?>"
        data-image-url="<?= $escaper->escapeHtmlAttr($block->getProductImageUrl()) ?>"
        data-price="<?= $escaper->escapeHtmlAttr($block->getProductFinalPrice()) ?>"
        data-currency="<?= $escaper->escapeHtmlAttr($block->getCurrentCurrency()) ?>">
     </div>
<?php endif; ?>
<!--/ Yotpo - Widget Div -->
